export function createPostToolUseHookScript(): string {
  return createHookScript("PostToolUse");
}

export function createStopHookScript(): string {
  return createHookScript("Stop");
}

function createHookScript(hookEventName: "PostToolUse" | "Stop"): string {
  return [
    "#!/usr/bin/env node",
    'import { spawnSync } from "node:child_process";',
    'import { readFileSync } from "node:fs";',
    "",
    `const hookEventName = ${JSON.stringify(hookEventName)};`,
    "const hookInput = readHookInput();",
    "",
    "if (hookEventName === \"Stop\" && hookInput.stop_hook_active === true) {",
    "  writeJson({ continue: true });",
    "  process.exit(0);",
    "}",
    "",
    "const voiceLintResult = runVoiceLint();",
    "writeJson(createHookOutput(voiceLintResult));",
    "process.exit(0);",
    "",
    "function readHookInput() {",
    "  try {",
    "    const inputText = readFileSync(0, \"utf8\");",
    "    return inputText.trim() === \"\" ? {} : parseHookInput(inputText);",
    "  } catch {",
    "    return {};",
    "  }",
    "}",
    "",
    "function parseHookInput(inputText) {",
    "  const inputValue = JSON.parse(inputText);",
    "  return inputValue !== null && typeof inputValue === \"object\" && !Array.isArray(inputValue)",
    "    ? inputValue",
    "    : {};",
    "}",
    "",
    "function runVoiceLint() {",
    "  const gitRoot = readGitRoot();",
    "  const result = spawnSync(\"npx\", [\"voicelint\", \"changed\", \"--format\", \"agent\"], {",
    "    cwd: gitRoot ?? process.cwd(),",
    "    encoding: \"utf8\",",
    "  });",
    "  return result.error === undefined",
    "    ? { kind: \"completed\", status: result.status ?? 2, stdout: result.stdout, stderr: result.stderr }",
    "    : { kind: \"unexpected\", details: result.error.message };",
    "}",
    "",
    "function readGitRoot() {",
    "  const result = spawnSync(\"git\", [\"rev-parse\", \"--show-toplevel\"], { encoding: \"utf8\" });",
    "  return result.status === 0 && result.stdout.trim() !== \"\" ? result.stdout.trim() : null;",
    "}",
    "",
    "function createHookOutput(voiceLintResult) {",
    "  if (voiceLintResult.kind === \"unexpected\") {",
    "    return createBlockOutput(`VoiceLint hook failed unexpectedly: ${voiceLintResult.details}`);",
    "  }",
    "",
    "  if (voiceLintResult.status === 0) {",
    "    return hookEventName === \"Stop\" ? { continue: true } : {};",
    "  }",
    "",
    "  if (voiceLintResult.status === 1) {",
    "    return createDiagnosticsBlockOutput(voiceLintResult);",
    "  }",
    "",
    "  if (voiceLintResult.status === 2) {",
    "    return createSetupFailureOutput(voiceLintResult);",
    "  }",
    "",
    "  return createBlockOutput(createUnexpectedExitReason(voiceLintResult));",
    "}",
    "",
    "function createDiagnosticsBlockOutput(voiceLintResult) {",
    "  const diagnosticsText = readCommandOutput(voiceLintResult);",
    "  const reason = hookEventName === \"Stop\"",
    "    ? `VoiceLint found issues. Run one more pass and fix these diagnostics before stopping:\\n\\n${diagnosticsText}`",
    "    : `VoiceLint found issues after file edits. Fix these diagnostics before continuing:\\n\\n${diagnosticsText}`;",
    "  return hookEventName === \"PostToolUse\"",
    "    ? createPostToolUseBlockOutput(reason, diagnosticsText)",
    "    : createBlockOutput(reason);",
    "}",
    "",
    "function createSetupFailureOutput(voiceLintResult) {",
    "  return createBlockOutput(`VoiceLint setup or config failed. Resolve this before continuing:\\n\\n${readCommandOutput(voiceLintResult)}`);",
    "}",
    "",
    "function createUnexpectedExitReason(voiceLintResult) {",
    "  return `VoiceLint hook failed unexpectedly with exit code ${voiceLintResult.status}:\\n\\n${readCommandOutput(voiceLintResult)}`;",
    "}",
    "",
    "function createPostToolUseBlockOutput(reason, diagnosticsText) {",
    "  return {",
    "    decision: \"block\",",
    "    reason,",
    "    hookSpecificOutput: {",
    "      hookEventName: \"PostToolUse\",",
    "      additionalContext: diagnosticsText,",
    "    },",
    "  };",
    "}",
    "",
    "function createBlockOutput(reason) {",
    "  return { decision: \"block\", reason };",
    "}",
    "",
    "function readCommandOutput(voiceLintResult) {",
    "  const outputText = `${voiceLintResult.stdout ?? \"\"}${voiceLintResult.stderr ?? \"\"}`.trim();",
    "  return outputText === \"\" ? \"No VoiceLint output was captured.\" : outputText;",
    "}",
    "",
    "function writeJson(outputValue) {",
    "  process.stdout.write(`${JSON.stringify(outputValue)}\\n`);",
    "}",
    "",
  ].join("\n");
}
