const helpLines = [
  "VoiceLint",
  "",
  "VoiceLint is a CLI linting system for natural-language text in software projects.",
  "",
  "Status:",
  "  v0.1.0 provides the TypeScript CLI, repo-local config loading,",
  "  baseline init scaffolding, input discovery, text segmentation,",
  "  YAML mechanical rule loading, and deterministic diagnostics for",
  "  path, changed, staged, and stdin modes.",
  "",
  "Usage:",
  "  voicelint [path ...] [--config PATH] [--format pretty|json|agent]",
  "  voicelint changed [--config PATH] [--format pretty|json|agent]",
  "  voicelint staged [--config PATH] [--format pretty|json|agent]",
  "  voicelint --stdin [--stdin-file-path PATH] [--config PATH] [--format pretty|json|agent]",
  "  voicelint init [--agent codex]",
  "  voicelint --help",
  "  voicelint --version",
  "",
  "Current behavior:",
  "  Supported input file types: .md, .mdx, .txt",
  "  Path, changed, staged, and stdin source discovery are implemented.",
  "  Markdown and plain-text segmentation with stable source locations is implemented.",
  "  Mechanical YAML rules support literal patterns, explicit regex, terms, and substitutions.",
  "  Lint commands emit deterministic pretty, json, and agent diagnostics.",
  "  `voicelint init` creates the repo-local config and baseline rule files.",
  "  `voicelint init --agent codex` still requires manual hook setup.",
  "",
  "Project:",
  "  https://github.com/DanielMulec/dm_voicelint",
  "",
];

export const createHelpText = (): string => helpLines.join("\n");
