const helpLines = [
  "VoiceLint",
  "",
  "VoiceLint is a CLI linting system for natural-language text in software projects.",
  "",
  "Status:",
  "  v0.0.5 provides the TypeScript CLI shell and input discovery for path,",
  "  changed, staged, and stdin modes.",
  "  Deterministic mechanical lint diagnostics are not implemented yet.",
  "",
  "Usage:",
  "  voicelint [path ...] [--config PATH] [--format pretty|json|agent]",
  "  voicelint changed [--config PATH] [--format pretty|json|agent]",
  "  voicelint staged [--config PATH] [--format pretty|json|agent]",
  "  voicelint --stdin [--stdin-file-path PATH] [--config PATH] [--format pretty|json|agent]",
  "  voicelint init [--agent codex]",
  "  voicelint --help",
  "  voicelint --version",
  "",
  "Current behavior:",
  "  Supported input file types: .md, .mdx, .txt",
  "  Path, changed, staged, and stdin source discovery are implemented.",
  "  Recognized lint commands currently report discovered sources and pending execution.",
  "",
  "Project:",
  "  https://github.com/DanielMulec/dm_voicelint",
  "",
];

export const createHelpText = (): string => helpLines.join("\n");
